### ISSUE TITLE
Gives some error. Any help?

### ISSUE THREAD

**Issue by NusryNizam** [clayrisser/react-gtk#18]
When installing the module, gives an error.

```
$ npm install --save @react-gtk/binding
npm WARN deprecated github@0.2.4: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)

> node-gtk@0.2.2 install /mnt/Files/Workspace/React Projects/gtkteste/gtktestapp/node_modules/node-gtk
> if [ "$(uname)" = "Darwin" ] && [ "$(which brew)" != "" ]; then export PKG_CONFIG_PATH=$(brew --prefix libffi)/lib/pkgconfig; fi; node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Tried to download(403): https://node-gtk-1.s3.amazonaws.com/node_gtk/v0.2.2/node_gtk-node-v72-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for node-gtk@0.2.2 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
Package gobject-introspection-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-introspection-1.0' found
gyp: Call to 'pkg-config --cflags gobject-introspection-1.0' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-28-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/mnt/Files/Workspace/React Projects/gtkteste/gtktestapp/node_modules/node-gtk/lib/binding/node-v72-linux-x64/node_gtk.node" "--module_name=node_gtk" "--module_path=/mnt/Files/Workspace/React Projects/gtkteste/gtktestapp/node_modules/node-gtk/lib/binding/node-v72-linux-x64" "--napi_version=5" "--node_abi_napi=napi"
gyp ERR! cwd /mnt/Files/Workspace/React Projects/gtkteste/gtktestapp/node_modules/node-gtk
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/mnt/Files/Workspace/React Projects/gtkteste/gtktestapp/node_modules/node-gtk/lib/binding/node-v72-linux-x64/node_gtk.node --module_name=node_gtk --module_path=/mnt/Files/Workspace/React Projects/gtkteste/gtktestapp/node_modules/node-gtk/lib/binding/node-v72-linux-x64 --napi_version=5 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/mnt/Files/Workspace/React Projects/gtkteste/gtktestapp/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 5.4.0-28-generic
node-pre-gyp ERR! command "/usr/bin/node" "/mnt/Files/Workspace/React Projects/gtkteste/gtktestapp/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /mnt/Files/Workspace/React Projects/gtkteste/gtktestapp/node_modules/node-gtk
node-pre-gyp ERR! node -v v12.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.10.2
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/mnt/Files/Workspace/React Projects/gtkteste/gtktestapp/node_modules/node-gtk/lib/binding/node-v72-linux-x64/node_gtk.node --module_name=node_gtk --module_path=/mnt/Files/Workspace/React Projects/gtkteste/gtktestapp/node_modules/node-gtk/lib/binding/node-v72-linux-x64 --napi_version=5 --node_abi_napi=napi' (1)
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-gtk@0.2.2 install: `if [ "$(uname)" = "Darwin" ] && [ "$(which brew)" != "" ]; then export PKG_CONFIG_PATH=$(brew --prefix libffi)/lib/pkgconfig; fi; node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-gtk@0.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by clayrisser** [comment]
Hmmm, looks like an issue with node-gtk.

https://github.com/romgrk/node-gtk#readme

I will go ahead and update that package and see if it helps.

Also, I'm in the process of refactoring this project. I've spent a year researching and closely following gtk and react, and I have a lot of great improvements.

**Comment by NusryNizam** [comment]
It works now. Thanks. 
btw, how can I buid/test the project? I'm new to this.

**Comment by clayrisser** [comment]
@NusryNizam can you send me a message at this link with your email, and I'll add you to the slack channel.

https://codejam.ninja/#hire

**Comment by AlexAtHome** [comment]
For those who still has the same issue:
I got this error during installation just now. Fixed it by switching to node v10

**Comment by clayrisser** [comment]
Thanks @mamoruuu
